{"name": "Проверяем падение ошибки 401 при получение заказа конкретного пользователя без токена авторизации", "status": "passed", "start": 1703950452448, "stop": 1703950452809, "uuid": "57f22cc6-ab24-44dd-ae92-aa0f9d9d01de", "historyId": "1df502a0b41ba27bf5a2a7ad08e4774e", "testCaseId": "1df502a0b41ba27bf5a2a7ad08e4774e", "fullName": "tests.test_retrieval_of_specific_user_orders.TestRetrievalOfCpecificUserOrder#test_retrieval_user_orders_with_authorization", "labels": [{"name": "parentSuite", "value": "tests"}, {"name": "suite", "value": "test_retrieval_of_specific_user_orders"}, {"name": "subSuite", "value": "TestRetrievalOfCpecificUserOrder"}, {"name": "host", "value": "b-ibragimov"}, {"name": "thread", "value": "46910-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "tests.test_retrieval_of_specific_user_orders"}]}